=== lucide-icons/lucide/icon.schema.json
{
  "$id": "https://lucide.dev/icons.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$vocabulary": {
    "https://json-schema.org/draft/2020-12/vocab/core": true,
    "https://json-schema.org/draft/2020-12/vocab/applicator": true,
    "https://json-schema.org/draft/2020-12/vocab/unevaluated": true,
    "https://json-schema.org/draft/2020-12/vocab/validation": true,
    "https://json-schema.org/draft/2020-12/vocab/meta-data": true,
    "https://json-schema.org/draft/2020-12/vocab/format-annotation": true,
    "https://json-schema.org/draft/2020-12/vocab/content": true
  },
  "title": "Lucide Icons icon schema",
  "type": "object",
  "additionalProperties": false,
  "required": ["$schema", "contributors", "categories", "tags", "use-cases"],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["name"],
        "properties": {
          "name": {
            "type": "string"
          },
          "deprecated": {
            "const": true
          },
          "deprecationReason": {
            "$ref": "#/$defs/aliasDeprecationReasons"
          },
          "toBeRemovedInVersion": {
            "$ref": "#/$defs/versionNumber",
            "description": "The version this icon will be removed in."
          }
        },
        "dependentRequired": {
          "deprecated": ["deprecationReason"],
          "deprecationReason": ["deprecated"],
          "toBeRemovedInVersion": ["deprecated"]
        }
      },
      "uniqueItems": true
    },
    "categories": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "string",
            "enum": [
              "accessibility",
              "account",
              "animals",
              "arrows",
              "buildings",
              "charts",
              "communication",
              "connectivity",
              "cursors",
              "design",
              "development",
              "devices",
              "emoji",
              "files",
              "finance",
              "food-beverage",
              "gaming",
              "home",
              "layout",
              "mail",
              "math",
              "medical",
              "multimedia",
              "nature",
              "navigation",
              "notifications",
              "people",
              "photography",
              "science",
              "seasons",
              "security",
              "shapes",
              "shopping",
              "social",
              "sports",
              "sustainability",
              "text",
              "time",
              "tools",
              "transportation",
              "travel",
              "weather"
            ]
          },
          {
            "type": "string",
            "pattern": "^\\$extends:"
          }
        ]
      },
      "uniqueItems": true
    },
    "contributors": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "use-cases": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 0,
      "uniqueItems": true
    },
    "deprecated": {
      "const": true
    },
    "deprecationReason": {
      "$ref": "#/$defs/iconDeprecationReasons"
    },
    "toBeRemovedInVersion": {
      "$ref": "#/$defs/versionNumber",
      "description": "The version this icon will be removed in."
    }
  },
  "dependentRequired": {
    "deprecated": ["deprecationReason"],
    "deprecationReason": ["deprecated"],
    "toBeRemovedInVersion": ["deprecated"]
  },
  "$defs": {
    "iconDeprecationReasons": {
      "type": "string",
      "enum": ["icon.renamed"]
    },
    "aliasDeprecationReasons": {
      "type": "string",
      "enum": ["alias.typo", "alias.name", "alias.duplicate"]
    },
    "versionNumber": {
      "type": "string",
      "pattern": "v[0-9]+(\\.[0-9]+)+"
    }
  },
  "description": "A JSON Schema for icons defined by Lucide Icons."
}

=== lucide-icons/lucide/icons/message-square-more.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "danielbayley",
    "karsa-mistmere"
  ],
  "use-cases": [],
  "tags": [
    "comment",
    "chat",
    "conversation",
    "dialog",
    "feedback",
    "speech bubble",
    "typing",
    "writing",
    "responding",
    "ellipsis",
    "etc",
    "et cetera",
    "...",
    "…"
  ],
  "categories": [
    "social"
  ]
}

=== lucide-icons/lucide/icons/list-chevrons-down-up.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "colebemis",
    "ericfennis",
    "ocavue",
    "jguddas",
    "PeterlitsZo",
    "mittalyashu",
    "juliankellydesign",
    "karsa-mistmere"
  ],
  "use-cases": [],
  "tags": [
    "options",
    "items",
    "collapse",
    "expand",
    "details",
    "disclosure",
    "show",
    "hide",
    "toggle",
    "accordion",
    "more",
    "less",
    "fold",
    "unfold",
    "vertical"
  ],
  "categories": [
    "text",
    "arrows"
  ]
}

=== lucide-icons/lucide/icons/pen-off.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "colebemis",
    "csandman",
    "mittalyashu",
    "ericfennis",
    "karsa-mistmere"
  ],
  "use-cases": [
    "Disabling editing or preventing user edits"
  ],
  "tags": [
    "disabled",
    "inactive",
    "non-editable",
    "locked",
    "read-only",
    "unmodifiable",
    "frozen",
    "restricted",
    "pencil",
    "change",
    "create",
    "draw",
    "writer",
    "writing",
    "biro",
    "ink",
    "marker",
    "felt tip",
    "stationery",
    "artist"
  ],
  "categories": [
    "text",
    "design",
    "tools"
  ]
}

=== lucide-icons/lucide/icons/circle-star.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "karsa-mistmere"
  ],
  "use-cases": [],
  "tags": [
    "badge",
    "medal",
    "honour",
    "decoration",
    "order",
    "pin",
    "laurel",
    "trophy",
    "medallion",
    "insignia",
    "bronze",
    "silver",
    "gold"
  ],
  "categories": [
    "sports",
    "gaming"
  ]
}

=== lucide-icons/lucide/icons/film.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "colebemis",
    "ericfennis",
    "danielbayley"
  ],
  "use-cases": [
    "Representing film, video, or cinema",
    "Indicating a movie or media library"
  ],
  "tags": [
    "movie",
    "video",
    "reel",
    "camera",
    "cinema",
    "entertainment"
  ],
  "categories": [
    "photography",
    "multimedia"
  ]
}

=== lucide-icons/lucide/icons/expand.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "mittalyashu",
    "ericfennis",
    "jguddas"
  ],
  "use-cases": [
    "Expanding content to fullscreen",
    "Maximizing or enlarging a view"
  ],
  "tags": [
    "scale",
    "fullscreen",
    "maximize",
    "minimize",
    "contract"
  ],
  "categories": [
    "text",
    "arrows"
  ]
}

=== lucide-icons/lucide/icons/banknote-arrow-up.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "AnnaSasDev",
    "joffx",
    "ericfennis",
    "mittalyashu"
  ],
  "use-cases": [
    "Indicating an increase in money, balance, or income in financial apps",
    "Signifying deposits, received payments, or monetary growth"
  ],
  "tags": [
    "bill",
    "currency",
    "money",
    "payment",
    "funds",
    "transaction",
    "cash",
    "finance",
    "deposit",
    "earnings",
    "income",
    "in",
    "credit",
    "prepaid",
    "growth",
    "increase"
  ],
  "categories": [
    "finance"
  ]
}

=== lucide-icons/lucide/icons/panel-top-dashed.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "danielbayley",
    "ericfennis",
    "irvineacosta"
  ],
  "use-cases": [],
  "tags": [
    "menu bar",
    "drawer",
    "show",
    "reveal",
    "padding",
    "margin",
    "guide",
    "layout",
    "bleed"
  ],
  "categories": [
    "layout"
  ],
  "aliases": [
    {
      "name": "panel-top-inactive",
      "deprecationReason": "alias.name",
      "deprecated": true
    }
  ]
}
