=== lucide-icons/lucide/icon.schema.json
{
  "$id": "https://lucide.dev/icons.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$vocabulary": {
    "https://json-schema.org/draft/2020-12/vocab/core": true,
    "https://json-schema.org/draft/2020-12/vocab/applicator": true,
    "https://json-schema.org/draft/2020-12/vocab/unevaluated": true,
    "https://json-schema.org/draft/2020-12/vocab/validation": true,
    "https://json-schema.org/draft/2020-12/vocab/meta-data": true,
    "https://json-schema.org/draft/2020-12/vocab/format-annotation": true,
    "https://json-schema.org/draft/2020-12/vocab/content": true
  },
  "title": "Lucide Icons icon schema",
  "type": "object",
  "additionalProperties": false,
  "required": ["$schema", "contributors", "categories", "tags", "use-cases"],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["name"],
        "properties": {
          "name": {
            "type": "string"
          },
          "deprecated": {
            "const": true
          },
          "deprecationReason": {
            "$ref": "#/$defs/aliasDeprecationReasons"
          },
          "toBeRemovedInVersion": {
            "$ref": "#/$defs/versionNumber",
            "description": "The version this icon will be removed in."
          }
        },
        "dependentRequired": {
          "deprecated": ["deprecationReason"],
          "deprecationReason": ["deprecated"],
          "toBeRemovedInVersion": ["deprecated"]
        }
      },
      "uniqueItems": true
    },
    "categories": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "string",
            "enum": [
              "accessibility",
              "account",
              "animals",
              "arrows",
              "buildings",
              "charts",
              "communication",
              "connectivity",
              "cursors",
              "design",
              "development",
              "devices",
              "emoji",
              "files",
              "finance",
              "food-beverage",
              "gaming",
              "home",
              "layout",
              "mail",
              "math",
              "medical",
              "multimedia",
              "nature",
              "navigation",
              "notifications",
              "people",
              "photography",
              "science",
              "seasons",
              "security",
              "shapes",
              "shopping",
              "social",
              "sports",
              "sustainability",
              "text",
              "time",
              "tools",
              "transportation",
              "travel",
              "weather"
            ]
          },
          {
            "type": "string",
            "pattern": "^\\$extends:"
          }
        ]
      },
      "uniqueItems": true
    },
    "contributors": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "use-cases": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 0,
      "uniqueItems": true
    },
    "deprecated": {
      "const": true
    },
    "deprecationReason": {
      "$ref": "#/$defs/iconDeprecationReasons"
    },
    "toBeRemovedInVersion": {
      "$ref": "#/$defs/versionNumber",
      "description": "The version this icon will be removed in."
    }
  },
  "dependentRequired": {
    "deprecated": ["deprecationReason"],
    "deprecationReason": ["deprecated"],
    "toBeRemovedInVersion": ["deprecated"]
  },
  "$defs": {
    "iconDeprecationReasons": {
      "type": "string",
      "enum": ["icon.renamed"]
    },
    "aliasDeprecationReasons": {
      "type": "string",
      "enum": ["alias.typo", "alias.name", "alias.duplicate"]
    },
    "versionNumber": {
      "type": "string",
      "pattern": "v[0-9]+(\\.[0-9]+)+"
    }
  },
  "description": "A JSON Schema for icons defined by Lucide Icons."
}

=== lucide-icons/lucide/icons/bubbles.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "vqh2602",
    "jguddas",
    "karsa-mistmere"
  ],
  "use-cases": [],
  "tags": [
    "water",
    "cleaning",
    "soap",
    "bath",
    "hygiene",
    "freshness",
    "wash",
    "foam",
    "cleanliness",
    "shampoo",
    "purity",
    "splash",
    "lightness",
    "airy",
    "relaxation",
    "spa",
    "bubbly",
    "fluid",
    "floating",
    "drop"
  ],
  "categories": [
    "weather"
  ]
}

=== lucide-icons/lucide/icons/kanban.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "danielbayley",
    "karsa-mistmere"
  ],
  "use-cases": [
    "Representing a kanban board or project view"
  ],
  "tags": [
    "projects",
    "manage",
    "overview",
    "board",
    "tickets",
    "issues",
    "roadmap",
    "plan",
    "intentions",
    "productivity",
    "work",
    "agile",
    "code",
    "coding"
  ],
  "categories": [
    "charts",
    "development",
    "design"
  ]
}

=== lucide-icons/lucide/icons/brain-circuit.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "karsa-mistmere",
    "jguddas",
    "it-is-not",
    "ericfennis"
  ],
  "use-cases": [],
  "tags": [
    "mind",
    "intellect",
    "artificial intelligence",
    "ai",
    "deep learning",
    "machine learning",
    "computing"
  ],
  "categories": [
    "science",
    "development"
  ]
}

=== lucide-icons/lucide/icons/square-sigma.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "danielbayley"
  ],
  "use-cases": [
    "Representing a sum or summation in math"
  ],
  "tags": [
    "sum",
    "calculate",
    "formula",
    "math",
    "enumeration",
    "enumerate"
  ],
  "categories": [
    "text",
    "math"
  ],
  "aliases": [
    {
      "name": "sigma-square",
      "deprecationReason": "alias.name",
      "deprecated": true,
      "toBeRemovedInVersion": "v1.0"
    }
  ]
}

=== lucide-icons/lucide/icons/circle-dot.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "karsa-mistmere"
  ],
  "use-cases": [],
  "tags": [
    "pending",
    "dot",
    "progress",
    "issue",
    "code",
    "coding",
    "version control",
    "choices",
    "multiple choice",
    "choose"
  ],
  "categories": [
    "development",
    "shapes"
  ]
}

=== lucide-icons/lucide/icons/chess-bishop.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "karsa-mistmere"
  ],
  "use-cases": [
    "Representing the bishop piece in chess applications",
    "Illustrating chess educational materials or algebraic notation"
  ],
  "tags": [
    "mitre",
    "miter",
    "piece",
    "board game",
    "religion"
  ],
  "categories": [
    "gaming",
    "emoji"
  ]
}

=== lucide-icons/lucide/icons/smile-plus.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "karsa-mistmere",
    "ericfennis"
  ],
  "use-cases": [],
  "tags": [
    "emoji",
    "face",
    "happy",
    "good",
    "emotion",
    "react",
    "reaction",
    "add"
  ],
  "categories": [
    "emoji",
    "social",
    "notifications",
    "communication"
  ]
}

=== lucide-icons/lucide/icons/disc.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "colebemis",
    "danielbayley",
    "jguddas",
    "ericfennis"
  ],
  "use-cases": [
    "Representing a music album, CD, or disc"
  ],
  "tags": [
    "album",
    "music",
    "songs",
    "format",
    "cd",
    "dvd",
    "vinyl",
    "sleeve",
    "cover",
    "platinum",
    "compilation",
    "ep",
    "recording",
    "playback",
    "spin",
    "rotate",
    "rpm",
    "dj"
  ],
  "categories": [
    "devices",
    "multimedia"
  ]
}
